### ISSUE TITLE
Stream error after 5 minutes

### ISSUE THREAD

**Issue by 172478394** [sashabaranov/go-openai#332]
I received the following error message 5 minutes after the stream was started. 
```
stream error: stream ID 53; INTERNAL_ERROR; received from peer
```
What is the reason, and may I recover from it?

**Comment by pmilanez** [comment]
I'm also having this error from time to time, my bet is on OpenAI instability but i was not able to close exactly on the problem.

**Comment by vvatanabe** [comment]
@172478394 @pmilanez The same problem has been reported in `openai/openai-python`. The cause is speculated to be on the server side of OpenAI.
refs: https://github.com/openai/openai-python/issues/399

**A temporary fix:**
> A temporary fix is to ask GPT-4 only to send you half of its response (and hoping it takes less than 5 minutes) and send you the remaining half when you prompt it "NEXT."

refs: https://github.com/openai/openai-python/issues/399#issuecomment-1566192612
