### ISSUE TITLE
Implement June OpenAI updates

### ISSUE THREAD

**Issue by sashabaranov** [sashabaranov/go-openai#360]
See updates at: https://openai.com/blog/function-calling-and-other-api-updates

From the top of my mind
- [x] Implement support for `*-0613` models (e.g. `gpt-4-0613`)
- [ ] Implement function calling

**Comment by vvatanabe** [comment]
Which fields in the `functions` are required or optional? It may be necessary to consider, for example, making the type pointer depending on the field.

refs: https://openai.com/blog/function-calling-and-other-api-updates
``` json
{
   "model":"gpt-3.5-turbo-0613",
   "messages":[
      {
         "role":"user",
         "content":"What is the weather like in Boston?"
      }
   ],
   "functions":[
      {
         "name":"get_current_weather",
         "description":"Get the current weather in a given location",
         "parameters":{
            "type":"object",
            "properties":{
               "location":{
                  "type":"string",
                  "description":"The city and state, e.g. San Francisco, CA"
               },
               "unit":{
                  "type":"string",
                  "enum":[
                     "celsius",
                     "fahrenheit"
                  ]
               }
            },
            "required":[
               "location"
            ]
         }
      }
   ]
}
```

**Comment by vvatanabe** [comment]
The official documentation related to `functions` has been updated.
https://platform.openai.com/docs/api-reference/chat/create#chat/create-name

**Comment by danielchristianschroeter** [comment]
https://platform.openai.com/docs/guides/gpt/function-calling

„note: the model may generate invalid JSON or hallucinate parameters“

Perhaps we should ensure that we handle this situation properly.

**Comment by stillmatic** [comment]
Could I suggest using the [jsonschema](https://github.com/invopop/jsonschema) library to construct JSONSchema, rather than reimplementing a fair bit of the spec? That library is well-tested and maintained and feels like a useful dependency to add, versus trying to check for edge cases.

I'm happy to make a PR that expects an input like https://github.com/stillmatic/gollum/blob/main/functions.go#L10 and simply adds the missing fields / updates enums, without additional logic.

It may be helpful to others: I've included an additional example of end-to-end parsing -- https://github.com/stillmatic/gollum/blob/a66a4664e02743c8b2e0b466493b9632af10d0de/functions_test.go#L135 . So you can take any Go json struct, generate the appropriate JSON schema for OpenAI, and parse the response back to the original struct. The implementation is extremely terse (I will replace the JSON validator stuff with the JSON schema validator) but probably should be standalone vs in this library.

**Comment by stillmatic** [comment]
It would be nice to use an external jsonschema library, a challenge with implementing a new one is the range of features to support, eg JSON Schema supports the 'example' field, even though it's not shown in the OpenAI docs, I suspect that the models would be able to make use of it. That being said, there are many competing libraries and it's probably hard to pick one which everyone would be happy with. 

I wonder if, since this library only needs to properly marshal the request, if it warrants a reimplementation of a very limited subset of JSON schema features -- eg no validation, no reflection etc, just defining the spec and asserting that inputs conform to that spec. 

WRT handling JSON -- I wrote an opinionated implementation for how to handle generating JSON schemas via reflection and parsing/validating them from string, see https://github.com/stillmatic/gollum/blob/main/functions_test.go#L133. The implementation itself is quite terse (~50 lines) but does make a fair number of assumptions (e..g that you have a `FunctionInput` struct for each function). IMO this logic is very useful but makes too many assumptions for a base library.

**Comment by cem-unuvar** [comment]
I saw that there was a new release (v1.11.0) with function calls implemented. However, they are not accessible in streaming responses. I couldn't find official OpenAI docs on this but [this](https://community.openai.com/t/function-calls-and-streaming/263393/2) seems to address the issue. I think this is an easy addition, *FunctionCall should be added as a field to ChatCompletionStreamChoiceDelta as far as I can tell

**Comment by stillmatic** [comment]
This PR https://github.com/sashabaranov/go-openai/pull/373 feels like a good example of why implementing JSONSchema is tricky. using `json.RawMessage` in the call should work, and will be more resilient to all the little edgecases to handle. 

I have a tested implementation here, which shows that you can successfully call OpenAI with the bytes array: https://github.com/stillmatic/gollum/commit/b10c270cc853054e0d8172ed1bd94c548f343b63/

**Comment by vvatanabe** [comment]
@stillmatic @jmacwhyte @sashabaranov 
Congrats! v1.11.3 has been released with #377. I've learned a lot from our discussions. Thank you!

**Comment by robinbraemer** [comment]
## Issue with `function_call`

As by OpenAI docs:
function_call is a string or object (Optional)

In the second case, we can't pass an object like:
```go
FunctionCall: `{"name": "extracted_offers_data"}`,
```

Since it would marshal the object into an escaped JSON string instead of a JSON object.

OpenAI returns:
```go
error, status code: 400, message: '$.function_call' is invalid. Please check the API reference: https://platform.openai.com/docs/api-reference.
```

**Comment by sashabaranov** [comment]
@robinbraemer Hey, we've just merged an [update](https://github.com/sashabaranov/go-openai/pull/377) that makes it `any` type. Could you please try with the `v1.11.3`?

Please see the [tests](https://github.com/sashabaranov/go-openai/pull/377/files#diff-035a00c5352f69159c65e81dbeffed087f0028e2a9324d7ff62786940f548827R71) for examples. We'll need to add some README examples for this!

**Comment by robinbraemer** [comment]
> v1.11.3
Seems to work!

**Comment by vvatanabe** [comment]
These features have already been released, so I'm closing this issue.
