### ISSUE TITLE
Modify assistant notice: invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by WangQuanTang** [sashabaranov/go-openai#836]
Your issue may already be reported!
Please search on the [issue tracker](https://github.com/sashabaranov/go-openai/issues) before creating one.

**Describe the bug**
When I do an update to assistant it says: "error, status code: 403, message: invalid character '<' looking for beginning of value"

**To Reproduce**
```
// UpdateAssistant update assistant
func (service *RemoteAssistantService) UpdateAssistant(ctx context.Context, updateAssistantReq UpdatedAssistantReq) error {
	tools, err := formatAssistantTools(updateAssistantReq.Tools)
	if err != nil {
		return err
	}

	toolResources, err := formatAssistantToolResources(updateAssistantReq.ToolResources)
	if err != nil {
		return err
	}

	assistantRequest := openai.AssistantRequest{
		Model:         updateAssistantReq.Model,
		Instructions:  &updateAssistantReq.Instructions,
		Name:          &updateAssistantReq.Name,
		Tools:         tools,
		ToolResources: &toolResources,
	}
	if updateAssistantReq.Instructions != "" {
		assistantRequest.Instructions = &updateAssistantReq.Instructions
	}

	_, err = service.OpenAiClient.ModifyAssistant(ctx, updateAssistantReq.AssistantAppId, assistantRequest)
	if err != nil {
		return err
	}

	return nil
}
```

**Expected behavior**
I tried to google some solutions. Some said it was because of the proxy, and some said it was a situation that could only be reproduced by chance. My previous project also used `go-openai`, `version v1.26.0`, and the same update operation was successful in the previous project. By printing the context, client and request parameters, they are almost the same. Therefore, I judged that there was no problem with my code, and it might be other abnormalities.
When I upgraded to v1.29.0, the issue still exists.

**Screenshots/Logs**
```
error, status code: 403, message: invalid character '<' looking for beginning of value
```

**Environment (please complete the following information):**
 - go-openai version: go-openai v1.27.0
 - Go version: version go1.22.5
 - OpenAI API version: [e.g. v2]
 - OS: [e.g. Ubuntu 20.04]

**Comment by gspeicher** [comment]
Oh, I just noticed error status code 403 in your log output. I see the problem now. That status code is `http.StatusForbidden` which means the response gets processed by [handleErrorResp](https://github.com/sashabaranov/go-openai/blob/643da8d650b1f7db4706076a53b9d0acddccbd17/client.go#L287) as called from [sendRequest](https://github.com/sashabaranov/go-openai/blob/643da8d650b1f7db4706076a53b9d0acddccbd17/client.go#L116).

That function attempts to parse the response body under the assumption that it's in JSON format, but the OpenAI API must be responding with HTML which is causing the JSON decoder to fail with this error message about the invalid character when it encounters an HTML tag.

Your problem seems to be that your API key isn't working. My problem must have been a sporadic service issue with the API. Maybe the failure result processing can be improved to make it more obvious what the problem is when this happens in either scenario.
